dbt_instacart:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '1998'
      port: 5432
      dbname: instacart
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      