dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost          
      port: 5432               
      user: postgres           
      password: 1998  
      dbname: instacart        
      schema: analytics       
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public
